workflows:
  ksign-ios:
    name: Build Ksign IPA
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    environment:
      xcode: latest
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
          
    scripts:
      - name: Initialize submodules
        script: |
          git submodule update --init --recursive
          
      - name: Download dependencies
        script: |
          make deps || true
          
      - name: Build iOS Archive
        script: |
          xcodebuild -project Ksign.xcodeproj \
            -scheme Ksign \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath build/Ksign.xcarchive \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM=""
            
      - name: Create unsigned IPA
        script: |
          mkdir -p packages
          cd build/Ksign.xcarchive/Products/Applications
          mkdir -p Payload
          cp -r Ksign.app Payload/
          zip -r ../../../../packages/Ksign.ipa Payload
          
    artifacts:
      - packages/Ksign.ipa
      - build/Ksign.xcarchive
      
    publishing:
      scripts:
        - name: Build complete
          script: |
            echo "Build completed successfully!"
            echo "IPA available at: packages/Ksign.ipa"
